"""Tests for zimbra-ssl.sh renewal logic, cron configuration, and certificate expiration checks.

Run: python3 -m unittest discover -s tests -v
"""
from datetime import datetime, timezone
import os
from pathlib import Path
import re
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / 'zimbra-ssl.sh'
SOURCE = SCRIPT.read_text()


class ZimbraSSLTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix='zimbra-ssl-test-')
        self.addCleanup(self.temporary.cleanup)
        self.tmp = Path(self.temporary.name)

    def test_bash_syntax_and_help(self):
        subprocess.run(['bash', '-n', str(SCRIPT)], check=True)
        result = subprocess.run(['bash', str(SCRIPT), '--help'], capture_output=True, text=True)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn('--renew', result.stdout)
        self.assertIn('--renew --force', result.stdout)
        self.assertIn('30', result.stdout)

    def test_cron_configuration_content(self):
        # Verify the cron string generated by install_automation
        self.assertIn('17 3 * * *', SOURCE)
        self.assertNotIn('17 3,15 * * *', SOURCE)
        self.assertIn('/var/log/zimbra-ssl-renew.log', SOURCE)

    def test_cert_checkend_logic(self):
        key_file = self.tmp / 'test.key'
        cert_60d = self.tmp / 'cert_60d.pem'
        cert_10d = self.tmp / 'cert_10d.pem'

        # Generate RSA private key
        subprocess.run(
            ['openssl', 'genrsa', '-out', str(key_file), '2048'],
            check=True, capture_output=True
        )

        # Generate certificate valid for 60 days
        subprocess.run(
            [
                'openssl', 'req', '-new', '-x509', '-key', str(key_file),
                '-out', str(cert_60d), '-days', '60',
                '-subj', '/CN=mail.example.com'
            ],
            check=True, capture_output=True
        )

        # Generate certificate valid for 10 days
        subprocess.run(
            [
                'openssl', 'req', '-new', '-x509', '-key', str(key_file),
                '-out', str(cert_10d), '-days', '10',
                '-subj', '/CN=mail.example.com'
            ],
            check=True, capture_output=True
        )

        threshold_seconds = 30 * 86400

        # For 60-day cert, openssl -checkend for 30 days should return 0 (still valid > 30 days)
        res_60d = subprocess.run(
            ['openssl', 'x509', '-checkend', str(threshold_seconds), '-noout', '-in', str(cert_60d)],
            capture_output=True
        )
        self.assertEqual(res_60d.returncode, 0, "60-day certificate should be recognized as still valid for > 30 days")

        # For 10-day cert, openssl -checkend for 30 days should return non-zero (expiring within 30 days)
        res_10d = subprocess.run(
            ['openssl', 'x509', '-checkend', str(threshold_seconds), '-noout', '-in', str(cert_10d)],
            capture_output=True
        )
        self.assertNotEqual(res_10d.returncode, 0, "10-day certificate should trigger renewal (expires in < 30 days)")


if __name__ == '__main__':
    unittest.main()
