"""Tests for zimbra-ssl.sh renewal logic, cron configuration, and certificate expiration checks.

Run: python3 -m unittest discover -s tests -v
"""
from datetime import datetime, timezone
import os
from pathlib import Path
import re
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / 'zimbra-ssl.sh'
SOURCE = SCRIPT.read_text()


class ZimbraSSLTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix='zimbra-ssl-test-')
        self.addCleanup(self.temporary.cleanup)
        self.tmp = Path(self.temporary.name)

    def test_bash_syntax_and_help(self):
        subprocess.run(['bash', '-n', str(SCRIPT)], check=True)
        result = subprocess.run(['bash', str(SCRIPT), '--help'], capture_output=True, text=True)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn('--renew', result.stdout)
        self.assertIn('--renew --force', result.stdout)
        self.assertIn('--disable-ldap-tls', result.stdout)
        self.assertIn('--enable-ldap-tls', result.stdout)
        self.assertIn('30', result.stdout)

    def test_ldap_tls_auto_fix_definitions(self):
        self.assertIn('readonly ZMLOCALCONFIG="/opt/zimbra/bin/zmlocalconfig"', SOURCE)
        self.assertIn('is_ldap_tls_error()', SOURCE)
        self.assertIn('is_ldap_tls_disabled()', SOURCE)
        self.assertIn('disable_ldap_tls()', SOURCE)
        self.assertIn('enable_ldap_tls()', SOURCE)

        # Verify disable configuration commands
        self.assertIn('ldap_starttls_required=false', SOURCE)
        self.assertIn('ldap_starttls_supported=0', SOURCE)
        self.assertIn('ldap_common_require_tls=0', SOURCE)

        # Verify enable configuration commands
        self.assertIn('ssl_allow_untrusted_certs=false', SOURCE)
        self.assertIn('ldap_starttls_supported=1', SOURCE)
        self.assertIn('ldap_starttls_required=true', SOURCE)

    def test_is_ldap_tls_error_pattern(self):
        exact_error = (
            "Unable to start TLS: SSL connect attempt failed error:0A000086:"
            "SSL routines::certificate verify failed when connecting to ldap master."
        )
        test_script = f"""
        is_ldap_tls_error() {{
          local output="$1"
          grep -qiE 'Unable to start TLS|certificate verify failed.*ldap|error:0A000086' <<< "$output"
        }}
        is_ldap_tls_error "{exact_error}"
        """
        res = subprocess.run(['bash', '-c', test_script], capture_output=True)
        self.assertEqual(res.returncode, 0, "is_ldap_tls_error should match the exact user error string")

        test_negative = """
        is_ldap_tls_error() {
          local output="$1"
          grep -qiE 'Unable to start TLS|certificate verify failed.*ldap|error:0A000086' <<< "$output"
        }
        is_ldap_tls_error "Connection refused on port 25"
        """
        res_neg = subprocess.run(['bash', '-c', test_negative], capture_output=True)
        self.assertNotEqual(res_neg.returncode, 0, "is_ldap_tls_error should not match unrelated error")

    def test_cron_configuration_content(self):
        # Verify the cron string generated by install_automation
        self.assertIn('17 3 * * *', SOURCE)
        self.assertNotIn('17 3,15 * * *', SOURCE)
        self.assertIn('/var/log/zimbra-ssl-renew.log', SOURCE)

    def test_force_renewal_passes_flag_to_certbot(self):
        self.assertIn('--force-renewal', SOURCE)
        self.assertIn('certbot_renew_args+=(--force-renewal)', SOURCE)

    def test_cert_checkend_logic(self):
        key_file = self.tmp / 'test.key'
        cert_60d = self.tmp / 'cert_60d.pem'
        cert_10d = self.tmp / 'cert_10d.pem'

        # Generate RSA private key
        subprocess.run(
            ['openssl', 'genrsa', '-out', str(key_file), '2048'],
            check=True, capture_output=True
        )

        # Generate certificate valid for 60 days
        subprocess.run(
            [
                'openssl', 'req', '-new', '-x509', '-key', str(key_file),
                '-out', str(cert_60d), '-days', '60',
                '-subj', '/CN=mail.example.com'
            ],
            check=True, capture_output=True
        )

        # Generate certificate valid for 10 days
        subprocess.run(
            [
                'openssl', 'req', '-new', '-x509', '-key', str(key_file),
                '-out', str(cert_10d), '-days', '10',
                '-subj', '/CN=mail.example.com'
            ],
            check=True, capture_output=True
        )

        threshold_seconds = 30 * 86400

        # For 60-day cert, openssl -checkend for 30 days should return 0 (still valid > 30 days)
        res_60d = subprocess.run(
            ['openssl', 'x509', '-checkend', str(threshold_seconds), '-noout', '-in', str(cert_60d)],
            capture_output=True
        )
        self.assertEqual(res_60d.returncode, 0, "60-day certificate should be recognized as still valid for > 30 days")

        # For 10-day cert, openssl -checkend for 30 days should return non-zero (expiring within 30 days)
        res_10d = subprocess.run(
            ['openssl', 'x509', '-checkend', str(threshold_seconds), '-noout', '-in', str(cert_10d)],
            capture_output=True
        )
        self.assertNotEqual(res_10d.returncode, 0, "10-day certificate should trigger renewal (expires in < 30 days)")


if __name__ == '__main__':
    unittest.main()
